In [116]:
import numpy as np
import math
np.set_printoptions(precision=5)

In [165]:
O = np.arange(1,4) # observation space
S = np.asarray(['H', 'C']) # State space
pi = np.asarray([0.8, 0.2]) # Initial probablity
Y = np.asarray([3, 1, 3]) # Observation sequnece T
A = np.array([[0.7, 0.3], 
              [0.4, 0.6]] ) # transition matrix
# A = np.matrix('0.7 0.6; 0.3 0.4') # transition matrix
B = np.matrix([[0.2, 0.4, 0.4],
               [0.5, 0.4, 0.1]]) # emission matrix 
print("O",O)
print("S",S)
print("pi",pi)
print("Y",Y)
print("A",A,'\n')
print("B",B)

O [1 2 3]
S ['H' 'C']
pi [0.8 0.2]
Y [3 1 3]
A [[0.7 0.3]
 [0.4 0.6]] 

B [[0.2 0.4 0.4]
 [0.5 0.4 0.1]]


In [272]:
N = len(O)
K = len(S)
T = len(Y)
T1 = np.zeros(shape=(K,T))
T2 = np.zeros(shape=(K,T))
for i in range(K):
    T1[i,0] = pi[i] * B[i, Y[0]-1] # or 0 = i-1
    T2[i,0] = 0
    
for j in range(1, T):    
    for i in range(K):
        T1[i,j] = np.max(T1[:,j-1] * A[:, i] * B[i, Y[j]-1])
        T2[i,j] = np.argmax(T1[:,j-1] * A[:, i] * B[i, Y[j]-1])

Z = [None] * T
X = [None] * T

Z[T-1] = np.argmax(T1[:,2])
X[T-1] = S[Z[T-1]]

for j in reversed(range(1, T)):
    Z[j-1] = T2[int(Z[j]),j]
    X[j-1] = S[int(Z[j-1])]

print(T1)
print(X)

[[0.32    0.0448  0.01254]
 [0.02    0.048   0.00288]]
['H', 'H', 'H']
